import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Updated to the new folder
const CONTENT_DIR = path.join(__dirname, '../src/content/artigos');
const OUTPUT_DIR = path.join(__dirname, '../src/data');
const CATALOG_FILE = path.join(OUTPUT_DIR, 'catalog.json');
const MAPPING_FILE = path.join(OUTPUT_DIR, 'mapping.ts');
const CHUNKS_DIR = path.join(OUTPUT_DIR, 'chunks');

if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}
if (!fs.existsSync(CHUNKS_DIR)) {
    fs.mkdirSync(CHUNKS_DIR, { recursive: true });
}

console.log('🏗️  Generating Content Catalog & Chunks from subdirectories...');

// Recursive read directory
function getFiles(dir, filesList = []) {
    if (!fs.existsSync(dir)) return filesList;
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const name = path.join(dir, file);
        if (fs.statSync(name).isDirectory()) {
            getFiles(name, filesList);
        } else if (name.endsWith('.md')) {
            filesList.push(name);
        }
    }
    return filesList;
}

const files = getFiles(CONTENT_DIR);
const catalog = [];
const mappingLines = [];

mappingLines.push('// Generated by scripts/generate-catalog.js');
mappingLines.push('// Do not edit manually');
mappingLines.push('');
mappingLines.push('export const ARTICLE_CONTENT_MAP: Record<string, () => Promise<{ default: { content: string } }>> = {');

files.forEach(filePath => {
    const fileContent = fs.readFileSync(filePath, 'utf-8');
    const { data, content } = matter(fileContent);

    if (!data.id) {
        console.warn(`⚠️  Skipping ${filePath}: Missing 'id' in frontmatter.`);
        return;
    }

    const plainText = content
        .replace(/!\[.*?\]\(.*?\)/g, '')
        .replace(/\[([^\]]+)\]\(.*?\)/g, '$1')
        .replace(/#{1,6}\s+/g, '')
        .replace(/(\*\*|__)(.*?)\1/g, '$2')
        .replace(/(\*|_)(.*?)\1/g, '$2')
        .replace(/`{3}[\s\S]*?`{3}/g, '')
        .replace(/`(.+?)`/g, '$1')
        .replace(/\n/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();

    const item = {
        ...data,
        fileName: path.basename(filePath),
        searchText: plainText
    };

    catalog.push(item);

    const chunkPath = path.join(CHUNKS_DIR, `${data.id}.json`);
    fs.writeFileSync(chunkPath, JSON.stringify({ content: content }));

    mappingLines.push(`  "${data.id}": () => import('./chunks/${data.id}.json'),`);
});

mappingLines.push('};');

fs.writeFileSync(CATALOG_FILE, JSON.stringify(catalog, null, 2));
console.log(`✅ Catalog generated with ${catalog.length} items at ${CATALOG_FILE}`);

fs.writeFileSync(MAPPING_FILE, mappingLines.join('\n'));
console.log(`✅ Lazy load mapping generated at ${MAPPING_FILE}`);
